name: movisens_flutter_example
description: An example on how to use the movisens_flutter Plugin.
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.1.0
  movisens_flutter:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
